#!/usr/bin/env bash
# Usage: pounce ssh <host>
# Summary: Open a secure shell on a Pitt CSC server
# Help: Opens a secure shell on a Pitt CSC server.
#
#   pounce ssh app-01
#   pounce ssh handy@app-01
set -e

GATEWAY_HOST="gateway.do-nyc3.pittcsc.org"
GATEWAY_PORT=56362

host="$1"
shift 1

ssh "$host" -t -o "ProxyCommand ssh -q -W %h:%p $GATEWAY_HOST -p $GATEWAY_PORT" "$@"
