#!/usr/bin/env bash
# Usage: pounce rails <app> <command> [options]
# Summary: Run a `rails` command for an app
# Help: Runs a `rails` command for the given app.
#
# Supports the following apps:
#
# * Handy
# * Heaven
#
# Supports the following commands:
#
# * console (c)
# * dbconsole (db)
set -e

app=$1
command=$2
shift 2

case "$app" in
  handy|Handy)
    user="handy"
    host="app-01"
    app_path="/u/apps/handy/current"
    ;;
  heaven|Heaven)
    user="heaven"
    host="app-01"
    app_path="/u/apps/heaven/current"
    ;;
  *)
    exec pounce-error "invalid Rails app"
esac

case "$command" in
  console|c) ;;
  dbconsole|db) ;;
  *)
    exec pounce-error "invalid Rails command"
esac

runner="cd $app_path && /bin/bash -lc 'bundle exec rails $command production $@'"

exec pounce-ssh "$user@$host" "$runner"
