#!/usr/bin/env bash
# Usage: pounce ssh <host>
# Summary: Open a secure shell on a Pitt CSC server
# Help: Opens a secure shell on a Pitt CSC server.
#
#   pounce ssh app-01
#   pounce ssh handy@app-01
set -e

GATEWAY="gateway.do-nyc3.pittcsc.org"

host="$1"
shift 1

ssh "$host" -t -o "ProxyCommand ssh -q -W %h:%p $GATEWAY" "$@"
