#!/usr/bin/env bash
# Usage: pounce console <app>
# Summary: Open a console for an app
# Help: Opens a production console for the given app.
#
# Supports the following apps:
#
# * Handy
set -e

app=$1

case "$app" in
  handy|Handy)
    exec pounce-rails "$app" console
    ;;
  *)
    exec pounce-error "invalid app"
esac
